spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&amp;characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 100000MB
mybatis:
  mapper-locations: classpath:Mapper/*Mapper.xml
  type-aliases-package: com.example.jwttest.entity
upload:
  path: C:\\Users\\dxc\\Desktop\\test\img\\
